hw-mgmt: sensors: Removing PSU power2_cap attribute
In most of the PSUs, 'power2_cap' PMBUS attribute is missing.
This is causing an issue while setting the sensor values using
sensors command.

root@cumulus:mgmt:/root# sensors -s -c /var/run/hw-management/config/lm_sensors_config
Error: Line 408: Unknown feature name
dps460-i2c-4-59: No such subfeature known

Bugs: #4663327

Signed-off-by: Ciju Rajan K <crajank@nvidia.com>